platform :ios, '10.0'
use_frameworks!

target 'TooltipImageView_Example' do
  pod 'TooltipImageView', :path => '../'

  target 'TooltipImageView_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 2'
    pod 'Nimble', '~> 8'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
      end
      config.build_settings['LD_RUNPATH_SEARCH_PATHS'] += ' $(FRAMEWORK_SEARCH_PATHS)'
    end
  end
end
