use_frameworks!

target 'TooltipImageView_Example' do
  pod 'TooltipImageView', :path => '../'

  target 'TooltipImageView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
